### ISSUE TITLE
After Decky Update v3.1.10 no achivements found

### ISSUE THREAD

**Issue by Deckpilot-coder** [EmuDeck/Emuchievements#58]
Hi after updating to decky v3.1.10 no achivements are loading anymore. 
API Login is active and possible. 
Tried to reinstall and clear cash and refresh but nothing fixed this.
Is this issue known so far? 
Thank you for your effort, greatest plugin.

**Comment by Deckpilot-coder** [comment]
i am the only one having the problem rn? - tried to install and load it again but when refreshing and clearing the cache i only get no achivements found for all games via emudeck

**Comment by JDLKMR** [comment]
> i am the only one having the problem rn? - tried to install and load it again but when refreshing and clearing the cache i only get no achivements found for all games via emudeck

You're not the only one, it's happening to me as well

**Comment by XcrysizZ** [comment]
Same, someone knows a fix?

**Comment by JDLKMR** [comment]
> Same, someone knows a fix?

If I had to guess, the plugin will need to be updated

**Comment by HeroProc** [comment]
Same issue. Things I've tried...

-Rolling back to 2.3.0
-Rolling back to both 2.5.0 prerelease versions on the teststore
-Full clearing Decky with a fresh install.

RA guys say there has been no API changes on their end. This much be a break that occurred either with 3.1.10 (or possibly Steam 3.7.13 as this issue has been going on now for what seems like about 2 months or so).

**Comment by nelsongt** [comment]
I have the issue and I'm still on SteamOS 3.6 branch, haven't updated to 3.7.13 yet.

Thanks for confirming no API change on RA side. I could try to bisect decky version with 3.1.9 to see if that's the smoking gun but by process of elimination it must be 3.1.10 update. I noticed that 3.1.10 changes some file permissions of the plugins, so it must be related to that. https://github.com/SteamDeckHomebrew/decky-loader/compare/v3.1.9...v3.1.10

**Comment by synthenese** [comment]
Hope this gets updated soon this was my favorite plugin

**Comment by mechrabbit25** [comment]
I have good news for anyone who hasn’t discovered this yet. Make sure you are logged into your RA account in the plugin. If you go to settings in the plugin you will find the Custom IDs Overrides tab. You will need to manually select each game you want to display achievements for along with the RA Id for each game. The RA Id can be found in the link of each game page on the retro achievements website. GameCube games also work for this but only for ciso files. I found that rvz files don’t work. Be sure to hit the save and refresh buttons afterwards to get everything to display.  Hope this helps.

**Comment by mrosenbergtech** [comment]
https://github.com/EmuDeck/Emuchievements/pull/59

https://github.com/EmuDeck/Emuchievements/pull/60

This has been addressed and the issue can likely be closed. Feel free to build from source until the plugin is updated in the testing store.

**Comment by Jaace** [comment]
I had to go to desktop mode, go to Home/emudeck/settings.sh and manually change my "achievementsUserToken" to my API Key. It was set to an old password or something? Anyway, emudeck does not seem to care and does not seem to update this file at all through its UI.

I still can't see the UI in the steam OS (game mode) but at least retroachievements and emuchievements logs in now...

UPDATE - it may be a bit more complex than that. It seems that EmuDeck has moved these configuration options to the .config directory now. The settings.json does not seem to stick. Fetching achievements via emuchievements comes back with no achievements found still, but at least the achievements still work on game load and playing the game.

**Comment by KP2048** [comment]
The EmuDeck specific configs are for EmuDeck, and have no bearing on Emuchievements. The plugin has JSON configs under ~/homebrew like every other decky plugin. Also achievementsUserToken is a login token generated when you authenticate using username and password via the API and is used by emulators, it's completely different from the API key, which is used by clients like Emuchievements. You can't use one for the other 
> I had to go to desktop mode, go to Home/emudeck/settings.sh and manually change my "achievementsUserToken" to my API Key. It was set to an old password or something? Anyway, emudeck does not seem to care and does not seem to update this file at all through its UI.
> 
> I still can't see the UI in the steam OS (game mode) but at least retroachievements and emuchievements logs in now...
> 
> UPDATE - it may be a bit more complex than that. It seems that EmuDeck has moved these configuration options to the .config directory now. The settings.json does not seem to stick. Fetching achievements via emuchievements comes back with no achievements found still, but at least the achievements still work on game load and playing the game.

**Comment by Jaace** [comment]
@KP2048 You're right and I forgot to update this thread after more poking around. Here's what I did that actually worked: https://github.com/EmuDeck/Emuchievements/issues/32#issuecomment-3378736344
